export const TOGGLE_APP_DRAWER = 'TOGGLE_APP_DRAWER';
export const SET_FEATURE_LOADING = 'SET_FEATURE_LOADING';
export const SET_APPLICATION_LOADING = 'SET_APPLICATION_LOADING';

export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const CLEAR_ALL_MESSAGE = 'CLEAR_ALL_MESSAGE';
export const ADD_SUCCESS_MSG = 'ADD_SUCCESS_MSG';
export const ADD_ERROR_MSG = 'ADD_ERROR_MSG';
export const ADD_WARNING_MSG = 'ADD_WARNING_MSG';
