export const RESET_AUTH_STATE = 'RESET_AUTH_STATE';
export const CURRENT_ACCOUNT = 'CURRENT_ACCOUNT';
export const ACCOUNT_PERMISSION = 'ACCOUNT_PERMISSION';

export const ACCESS_TOKEN = 'ACCESS_TOKEN';
export const TOKEN_EXPIRED_IN = 'TOKEN_VALID_IN';
export const TOKEN_LAST_ACCESS = 'TOKEN_LAST_ACCESS';
