export const DOCUMENT_STATUS = {
  ORIGINAL: 'ORIGINAL',
  VALID: 'VALID',
  INVALID: 'INVALID',

  SENDING: 'SENDING',
  RECEIVED: 'RECEIVED',
  DISTRIBUTED: 'DISTRIBUTED',

  DEFER: 'DEFER',
  MODIFIED: 'MODIFIED',

  PASS: 'PASS',
  CANCEL: 'CANCEL',
  CANCEL_AUTO: 'CANCEL_AUTO',
  CANCEL_STEP_RECEIVED: 'CANCEL_STEP_RECEIVED',
  CANCEL_STEP_PASS: 'CANCEL_STEP_PASS'
};
