export const ALL_PARAMETERS = 'ALL_PARAMETERS';
export const PARAM_DEADLINE = 'PARAM_DEADLINE';
export const PARAM_FETCHING = 'PARAM_FETCHING';
export const DOCUMENT_DEADLINE = 'DOCUMENT_DEADLINE';
export const PERIODIC_FETCH_NOTIFY = 'PERIODIC_FETCH_NOTIFY';
